### ISSUE TITLE
Wrong years displayed with minDate and maxDate

### ISSUE THREAD

**Issue by alfredfriedrich** [Wikiki/bulma-calendar#117]
## Bug Report

**Environment**
- Extension version(s): v5.0.2
- Bulma version: 0.7.1
- OS: OSX
- Browser: all
- Are customizing the extension: no

**Current Behavior**
When giving a minDate and maxDate option, the years array is filled wrong. E.g. minDate is now - 100 years and maxDate is now, it will show years from 1867 to 1966. Also the starting Date is not now (although provided) but minDate.

**Input Code**
- Initialization code:

```js
  const today = new Date();
  const minDate = new Date(today.getFullYear() - 100, today.getMonth(), today.getDay());
  const calendars = bulmaCalendar.attach('[type="date"]', {
    lang: 'en',
    displayMode: 'dialog',
    showFooter: false,
    showHeader: false,
    startDate: today,
    maxDate: today,
    minDate: minDate,
  });

```

**Additional context/Screenshots**
When calendar is opened:
![bulma-calendar-init-ui](https://user-images.githubusercontent.com/28871739/48073870-ed4cf380-e1df-11e8-96ed-4df260bdfa3c.png)
Begin of years select:
![bulma-calendar-years-begin](https://user-images.githubusercontent.com/28871739/48073894-f938b580-e1df-11e8-92d9-533a2c5e7783.png)
End of years:
![bulma-calendar-years-end](https://user-images.githubusercontent.com/28871739/48073910-035ab400-e1e0-11e8-93ec-2127861f254b.png)

Demo: https://codepen.io/anon/pen/VVvYVv?editors=1000

**Comment by Wikiki** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by Wikiki** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Wikiki/bulma-calendar/issues/111 (minDate and maxDate visual bug), https://github.com/Wikiki/bulma-calendar/issues/28 (Add "minDate" and "maxDate" options), https://github.com/Wikiki/bulma-calendar/issues/43 (maxDate not working), https://github.com/Wikiki/bulma-calendar/issues/72 (Wrong date on input value.), and https://github.com/Wikiki/bulma-calendar/issues/40 (Year buttons not appearing).

**Comment by alfredfriedrich** [comment]
Thanks for the fast fix, unfortunately the codepen demo above throws an error now:
`TypeError: f.slice is not a function bulma-calendar.min.js:1:5935`
After updating to 5.0.3 my local dev env produces the same error in
`node_modules/date-and-time/date-and-time.js:114`
The error results when parsing a Date Object (instead of a string). 

I also tried with Strings instead of Dates, but that results in another error (`RangeError: invalid array length` in the `_renderDays` function).

Did I overlook something?

**Comment by Wikiki** [comment]
I'll check that

**Comment by alfredfriedrich** [comment]
Thank you! 
It was unclear to me that maxDate/minDate are strings vs. startDate/endDate being Dates.

**Comment by Wikiki** [comment]
I will update the doc to clarify that point. Thanks for your feedback

**Comment by pdrhlik** [comment]
Hi there, @Wikiki, @alfredfriedrich, @michael-hack,

I'm still having this issue in v6.1.19. It's not possible to set minDate and maxDate to string now. Any advice?
